/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public static void main(String[] args){
        Restaurant applebees = new Restaurant("Applebees", 2);
//        System.out.println(applebees.toString());

        Review gordonRamsay = new Review("Gordon Ramsay", 1, "THIS PLACE SUCKS");
//        System.out.println(gordonRamsay.toString() );
        Review gordonRamsay1 = new Review("Gordon Ramsay", 4, "THIS PLACE SUCKS");
//        System.out.println(gordonRamsay.toString() );
        Review gordonRamsay2 = new Review("Gordon Ramsay", 5, "THIS PLACE SUCKS");
//        System.out.println(gordonRamsay.toString() );

        applebees.addReview(gordonRamsay);
        applebees.addReview(gordonRamsay1);
        applebees.addReview(gordonRamsay2);
        System.out.println(applebees);
    }
}
