/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package objects;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        Bag bag = new Bag();
        Pencil pencil = new Pencil("green", false, 4, true);
        Marker marker = new Marker("Blue", true, 10, true);

        bag.bag.add(pencil);
        bag.bag.add(marker);

        for (WritingObject writingObject : bag.bag) {
            if (writingObject instanceof Pencil) {
                System.out.println("There is a pencil in the bag");
            } else {
                System.out.println("This is not a pencil");
            }
        }
        System.out.println(pencil.toString());
    }
}
